package com.scrumPoker.domain;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Identify entity, resolve id as main field.
 * @author Maxim Korkuts
 */
public abstract class Identify {

    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    public Identify() {
    }

    public Identify(long id) {
        this.id = id;
    }

    /**getters and setters*/
    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }
}
